#!/bin/bash
## ┃┏━ ┏━┛━┏┛┏━┃┃  ┃  ┏━┛┏━┃
## ┃┃ ┃━━┃ ┃ ┏━┃┃  ┃  ┏━┛┏┏┛
## ┛┛ ┛━━┛ ┛ ┛ ┛━━┛━━┛━━┛┛ ┛
#
# Warna
MER=$(tput setaf 1)
KUN=$(tput setaf 3)
HIJ=$(tput setaf 2)
BRU=$(tput setaf 4)
BLD=$(tput bold)
RST=$(tput sgr0)

ERROR_LOG="$HOME/RiceError.log"

logo () {
	local text="${1:?}"
	echo -en "
               %%                   
          #%#####*+=                
          @@%@@@@%%#%%              
           %%%%%%%                  
         ##%%%%%###                 
         @%%%%%%%#+#                
         @%%@@@%#**                  
         %%@@@@@%#*  **              
       %%%@@@@@@%%###%               
     %%%%%@@@@@@@%%#   ###          
    %% %%%@@@@@@@@%##%%%%           
   %% %%%@@@@@@@%%%%%               
   %%%%%%%%%@@%%####                
   %%%%%@@@@%%%@@@%%%               
    %%%%%%%@@@@@@%%%%               
    ###%%%@@@@@%@%%%%%              
  ## ###%%%@@@@@@@%#                
       # %%@@@%%%%%                 
           %%%%%%%%                 
           ####%%##*#               
              #####%%%              
      Dotfiles "${HIJ}"Termux"${RST}"\n\n"
}

logo "Welcome!"
while true; do
    read -rp " Do you wish to continue? [y/N]: " yn
    case $yn in
        [Yy]* ) break ;;
        [Nn]* ) exit ;;
        * ) printf " Error: just write 'y' or 'n'\n\n" ;;
    esac
done

# Daftar package untuk Termux
dependency=(bat eza neofetch screenfetch git proot-distro termux-api vim wget zsh)

is_installed() {
    command -v "$1" >/dev/null 2>&1 || dpkg -s "$1" >/dev/null 2>&1
}

printf "%s%sChecking for required packages...%s\n" "${BLD}" "${BRU}" "${RST}"
for package in "${dependency[@]}"; do
    if ! is_installed "$package"; then
        if pkg install -y "$package" >/dev/null 2>> "$ERROR_LOG"; then
            printf "%s%s%s %shas been installed successfully.%s\n" "${BLD}" "${KUN}" "$package" "${BRU}" "${RST}"
        else
            printf "%s%s%s %shas not been installed correctly. See %sRiceError.log %sfor more details.%s\n" "${BLD}" "${KUN}" "$package" "${MER}" "${BRU}" "${MER}" "${RST}"
        fi
    else
        printf '%s%s%s %sis already installed on your system!%s\n' "${BLD}" "${KUN}" "$package" "${HIJ}" "${RST}"
    fi
done

logo "Downloading dotfiles"
repo_url="https://github.com/adilhyz/dotfiles-termux"
repo_dir="$HOME/dotfiles-termux"

if [ -d "$repo_dir" ]; then
    printf "Removing existing dotfiles repository\n"
    rm -rf "$repo_dir"
fi

printf "Cloning dotfiles from %s\n" "$repo_url"
git clone --depth=1 "$repo_url" "$repo_dir"
cp -f "$HOME/dotfiles-termux/home/.zshrc" "$HOME"
fc-cache -rv >/dev/null 2>&1
printf "%s%sFiles copied successfully!!%s\n" "${BLD}" "${HIJ}" "${RST}"
printf "%s%sDone!!%s\n\n" "${BLD}" "${HIJ}" "${RST}"

logo "Changing default shell to zsh"
echo "exec zsh" >> "$HOME/.zshrc"
printf "%s%sYour shell is now set to zsh. Restart Termux to apply changes!%s\n" "${BLD}" "${HIJ}" "${RST}"

sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" --skip-chsh --unattended && zsh